<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoWork.Domain\CoWork.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="11.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Reservations\Command\CancelReservation\" />
    <Folder Include="Features\Reservations\Command\PayReservation\" />
    <Folder Include="Features\Reservations\Query\" />
  </ItemGroup>

</Project>
