<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoWork.Application\CoWork.Application.csproj" />
    <ProjectReference Include="..\CoWork.Domain\CoWork.Domain.csproj" />
    <ProjectReference Include="..\CoWork.Infrastructure\CoWork.Infrastructure.csproj" />
  </ItemGroup>

</Project>
